[package]
name = "rust_deps"
version = "0.1.0"
authors = ["Olek <ntszar@gmail.com>"]

[dependencies]
rust_dep_on_err_prop_0_01 = { path = "rust_dep_on_err_prop_0_01" }
rust_dep_on_err_prop_0_02 = { path = "rust_dep_on_err_prop_0_02" }
